server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ms-ne-exchange-rate
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:exchangeDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  h2:
    console:
      settings:
        trace: true
      enabled: true
      path: /h2-console

app:
  jwt:
    key: 5pAq6zRyX8bC3dV2wS7gN1mK9jF0hL4tUoP6iBvE3nG8xZaQrY7cW2fA # according to SHA-256 requirements
    algorithm: HS256
    issuer: http://localhost:8080
    expiresIn: 5m


